<?xml version="1.0" encoding="UTF-8"?><html><head><meta charset="UTF-8"/><link href="../../styles/md-scroll.css" media="screen, projection, print" rel="stylesheet" type="text/css"/><link href="../../styles/md-scroll-ext.css" media="screen, projection, print" rel="stylesheet" type="text/css"/><meta content="width=device-width, initial-scale=1" name="viewport"/><link href="https://www.cs.odu.edu/~zeil/styles/highlight.js/styles/googlecode.css" rel="stylesheet"/><script src="https://www.cs.odu.edu/~zeil/styles/highlight.js/highlight.pack.js"> </script><script>hljs.initHighlightingOnLoad();</script><script src="../../styles/md-scroll.js" type="text/javascript"> </script><script src="../../styles/md-scroll-ext.js" type="text/javascript"> </script><script src="../../styles/rawdeflate.js" type="text/javascript"> </script><script src="../../styles/plantuml.js" type="text/javascript"> </script><script src="../../styles/mermaid.min.js" type="text/javascript"> </script><script type="text/javascript">
             window.MathJax = {
               tex2jax: {
               inlineMath: [ ['$','$'], ["\\(","\\)"] ],
               processEscapes: true
             }
           };
           </script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS-MML_HTMLorMML" type="text/javascript"> </script><title>Basic Exceptions</title></head><body><script>sshowControl0 = { counter: 1,
             showNumber: 0, max: 1};
             window.onhashchange = hashHasChanged;</script><div class="navHeader" id="slideshowControlA0"><table class="navHeader"><tr class="slideshowcontrol"><td class="slideshowcontrolLeft"/><td class="slideshowcontrolMiddle">
<a class="imgLink" href="../../Directory/outline/index.html" title="Course home/outline"><img src="../../graphics/home.png"/></a>
<a href="mailto:tkennedy@odu.edu?subject=CS263%2C%20Basic%20Exceptions"><img src="../../graphics/email.png" title="Email to instructor"/></a><span style="margin: 0 32px;"/></td><td class="slideshowcontrolRight"/></tr></table></div><div class="mainBody"><div class="titleblock"><h1 class="title">Basic Exceptions</h1><h2 class="author">Thomas J. Kennedy</h2></div><div class="toc">Contents:<div class="toc-h1"><a href="#what-is-an-exception-">1 What is an Exception?</a></div><div class="toc-h1"><a href="#why-so-specific-">2 Why so Specific?</a></div><div class="toc-h1"><a href="#what-is-the-as-for-">3 What is the “as” For?</a></div></div><p>In most courses you are told to <em>assume all input is well formed</em>. You are told to write minimal (if any) error handling code.</p>
    <a id="whatisanexception"/><h1 id="what-is-an-exception-">1 What is an Exception?</h1><p>As exception can interupt the execution flow of a program. In the case of a try-except block…</p>
    <pre><code class="python">try:
    raw_string = input("Enter a year: ")
    year = int(raw_string)

except ValueError as _err:
    print(f'"{raw_string}" is not a valid year')
</code></pre><p>we essentially have an if-else analogue. The <code>try</code> block is the <em>good</em> path and the <code>except</code> block is the <em>bad</em> path.</p>
    <a id="whysospecific"/><h1 id="why-so-specific-">2 Why so Specific?</h1><p>You may have noticed that the try-catch block only handles the <code>ValueError</code> exception. Let us rewrite the code with a bare exception.</p>
    <pre><code class="python">try:
    raw_string = input("Enter a year: ")
    year = int(raw_string)

except:
    print(f'"{raw_string}" is not a valid year')
</code></pre><p>Run the code and press <code>ctrl-c</code> to force exit. You will see the following…</p>
    <blockquote>
  <pre><code>Enter a year. ^CTraceback (most recent call last):
  File "/home/tkennedy/Courses/Reviews/cs263/Module-07/exception_ex_1.py", line 4, in main
    raw_string = input("Enter a year. ")

KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tkennedy/Courses/Reviews/cs263/Module-07/exception_ex_1.py", line 12, in &lt;module&gt;
    main()
  File "/home/tkennedy/Courses/Reviews/cs263/Module-07/exception_ex_1.py", line 8, in main
    print(f'"{raw_string}" is not a valid year')

UnboundLocalError: cannot access local variable 'raw_string' where it is not associated with a value
</code></pre>
</blockquote><p>We caught the <code>KeyboardInterrupt</code>. Our intention was to handled malformed year input, but we wrote code that handles every possible exception that can occur. Let us only handle <code>ValueError</code>s…</p>
    <pre><code class="python">try:
    raw_string = input("Enter a year: ")
    year = int(raw_string)

except ValueError:
    print(f'"{raw_string}" is not a valid year')
</code></pre><p>Our output is now…</p>
    <blockquote>
  <pre><code>Enter a year: ^CTraceback (most recent call last):
  File "/home/tkennedy/Courses/Reviews/cs263/Module-07/exception_ex_2.py", line 12, in &lt;module&gt;
    main()
  File "/home/tkennedy/Courses/Reviews/cs263/Module-07/exception_ex_2.py", line 4, in main
    raw_string = input("Enter a year: ")

KeyboardInterrupt
</code></pre>
</blockquote><p>While this example might demonstrate a small inconvenience… imagine debugging that in a larger program within function that is multiple function calls deep.</p>
    <a id="whatistheasfor"/><h1 id="what-is-the-as-for-">3 What is the “as” For?</h1><p>That leaves the <code>as _err</code>. Sometimes you want to perform further handling of an error. <em>For the moment… let us acknowledge that additional handling is possible while deferring further discussion.</em></p>
    <pre><code class="python">def main():

    try:
        raw_string = input("Enter a year: ")
        year = int(raw_string)

    except ValueError as _err:
        print(f'"{raw_string}" is not a valid year')


if __name__ == "__main__":
    main()
</code></pre><p>The underscore indicates that, by convention the <code>_err</code> variable while named… is not used. <em>In general a variable that starts with an underscore is understood to be needed syntacticly, but is not used in the code.</em> An example of this is shown in the following code snippet.</p>
    <pre><code class="python">for _ in range(1, 4):
    print("Hello!)
</code></pre><p>The loop prints <code>"Hello!</code>" four (4) times. While a variable is need to control the loop, the actual loop count is never used.</p>
    </div><script>sshowControl0 = { counter: 1,
             showNumber: 0, max: 1};
             window.onhashchange = hashHasChanged;</script><div class="navFooter" id="slideshowControl0"><table class="navFooter"><tr class="slideshowcontrol"><td class="slideshowcontrolLeft"/><td class="slideshowcontrolMiddle">
<a class="imgLink" href="../../Directory/outline/index.html" title="Course home/outline"><img src="../../graphics/home.png"/></a>
<a href="mailto:tkennedy@odu.edu?subject=CS263%2C%20Basic%20Exceptions"><img src="../../graphics/email.png" title="Email to instructor"/></a><span style="margin: 0 32px;"/></td><td class="slideshowcontrolRight"/></tr></table></div><div class="copyright">© 2015-2025, Old Dominion Univ.</div></body></html>
